#!/bin/bash
# setup.sh - Set up worktree commands for Unix/Mac/WSL
#
# This creates wt-config.sh with the correct paths for your machine.

echo "Setting up worktree commands for this machine..."
echo

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKTREE_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

echo "Creating config file..."
cat > "$SCRIPT_DIR/wt-config.sh" << EOF
#!/bin/bash
# Worktree Management Config - Machine Specific
# Generated by setup.sh - DO NOT COMMIT

export SCRIPTS_PATH="$SCRIPT_DIR"
export WORKTREE_ROOT="$WORKTREE_ROOT"
EOF

chmod +x "$SCRIPT_DIR/wt-config.sh"

echo
echo "========================================"
echo "Setup complete!"
echo "========================================"
echo
echo "Config file created: $SCRIPT_DIR/wt-config.sh"
echo "Scripts path: $SCRIPT_DIR"
echo "Worktree root: $WORKTREE_ROOT"
echo
echo "To use the worktree commands, add this to your ~/.bashrc or ~/.zshrc:"
echo "  source \"$SCRIPT_DIR/wt-profile.sh\""
echo
